version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: eisenhower_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - eisenhower_net
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}

  backend:
    build:
      context: ./backend
    container_name: eisenhower_backend
    networks:
      - eisenhower_net

  frontend:
    build:
      context: ./frontend
    container_name: eisenhower_frontend
    depends_on:
      - backend
    networks:
      - eisenhower_net

  certbot:
    image: certbot/certbot
    container_name: eisenhower_certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - eisenhower_net

networks:
  eisenhower_net:
    driver: bridge
